[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = ".netlify/functions/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=./"

# Environment variables will be injected by Netlify's UI
# and won't be exposed in the built files

[dev]
  framework = "vite"
  target = "src"
  port = 8080

[context.production.environment]
  NODE_ENV = "production"

# Disable Next.js plugin as this is a Vite project
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
