[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Environment variables will be injected by Netlify's UI
# and won't be exposed in the built files

[dev]
  framework = "vite"
  target = "src"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"
