[build]
  command = "npm install --omit=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 5173
  framework = "vite"
  target = "src"
